force-app/main/default/objects/CAS_Page_Detail__c/CAS_Page_Detail__c.object-meta.xml
<CustomObject>
    <label>Page Detail</label>
    <nameField>
        <label>CAS Page Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CAS_Page_Detail__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <label>Default</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAS_Page_Detail__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAS_Page_Detail__c/fields/Page_Template__c.field-meta.xml
<CustomField>
    <fullName>Page_Template__c</fullName>
    <label>Page Template</label>
    <referenceTo>CAS_Page_Template__c</referenceTo>
    <relationshipName>CAS_Page_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CAS_Page_Detail__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAS_Page_Detail__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CAS_Page_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Field_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAS_Page_Template__c/CAS_Page_Template__c.object-meta.xml
<CustomObject>
    <label>Page Template</label>
    <nameField>
        <label>CAS Page Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAS_Page_Template__c/fields/Page_columns__c.field-meta.xml
<CustomField>
    <fullName>Page_columns__c</fullName>
    <label>Page columns</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Page_columns</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAS_Page_Template__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Field_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>date</fullName>
    </customValue>
    <customValue>
        <fullName>lookup</fullName>
    </customValue>
    <customValue>
        <fullName>lookup fixed</fullName>
    </customValue>
    <customValue>
        <fullName>none</fullName>
    </customValue>
    <customValue>
        <fullName>number</fullName>
    </customValue>
    <customValue>
        <fullName>phone</fullName>
    </customValue>
    <customValue>
        <fullName>picklist</fullName>
    </customValue>
    <customValue>
        <fullName>picklist lookup</fullName>
    </customValue>
    <customValue>
        <fullName>text</fullName>
        <default>true</default>
        <label>text</label>
    </customValue>
    <customValue>
        <fullName>url</fullName>
    </customValue>
    <customValue>
        <fullName>currency</fullName>
    </customValue>
    <masterLabel>Field Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Page_columns.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <masterLabel>Page columns</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CAS_PageController.cls
public with sharing class CAS_PageController {
    
    public class clTemplate {
    	@AuraEnabled public String Name;
    	@AuraEnabled public String Label;
    	@AuraEnabled public String Type;
    	@AuraEnabled public String DefaultValue;
    	@AuraEnabled public Boolean Required;

    	public clTemplate(string v1, string v2, string v3, string v4, boolean v5) {
    		Name = v1;
    		Label = v2;
    		Type = v3;
    		DefaultValue = v4;
    		Required = v5;
    	}
    }

	@AuraEnabled
    public static List<clTemplate> LoadTemplateDetail(string v_object, string v_template) {
    	List<clTemplate> ret = new list<clTemplate>();

		for (CAS_Page_Detail__c fso: 	[SELECT Name, Type__c, Default__c, Required__c, Label__c 
							FROM CAS_Page_Detail__c
							WHERE Page_Template__r.Object__c = :v_object
							AND Page_Template__r.Name = :v_template
							ORDER BY Sequence__c]) {
	
		   	clTemplate tmp = new clTemplate(fso.Name, fso.Label__c, fso.Type__c, fso.Default__c,fso.Required__c);
	    	ret.add(tmp);

		}
 
    	return ret;

    }


	@AuraEnabled
    public static List<string> LoadTemplates(string v_object) {
    	List<string> ret = new list<string>();

    	for (sobject fso : [select Name,Page_columns__c 
    						from CAS_Page_Template__c 
    						where Object__c = :v_object
    						order by Sequence__c]) {
    		ret.add((string) fso.get('Name'));

    	}
    	if (ret.size() == 0) ret.add('NO TEMPLATES');
    	return ret;
    }


}